const rouletteWheel = [
    { number: '0', color: ':green_circle:' },
    { number: '32', color: ':red_circle:' },
    { number: '15', color: ':black_circle:' },
    { number: '19', color: ':red_circle:' },
    { number: '4', color: ':black_circle:' },
    { number: '21', color: ':red_circle:' },
    { number: '2', color: ':black_circle:' },
    { number: '25', color: ':red_circle:' },
    { number: '17', color: ':black_circle:' },
    { number: '34', color: ':red_circle:' },
    { number: '6', color: ':black_circle:' },
    { number: '27', color: ':red_circle:' },
    { number: '13', color: ':black_circle:' },
    { number: '36', color: ':red_circle:' },
    { number: '11', color: ':black_circle:' },
    { number: '30', color: ':red_circle:' },
    { number: '8', color: ':black_circle:' },
    { number: '23', color: ':red_circle:' },
    { number: '10', color: ':black_circle:' },
    { number: '5', color: ':red_circle:' },
    { number: '24', color: ':black_circle:' },
    { number: '16', color: ':red_circle:' },
    { number: '33', color: ':black_circle:' },
    { number: '1', color: ':red_circle:' },
    { number: '20', color: ':black_circle:' },
    { number: '14', color: ':red_circle:' },
    { number: '31', color: ':black_circle:' },
    { number: '9', color: ':red_circle:' },
    { number: '22', color: ':black_circle:' },
    { number: '18', color: ':red_circle:' },
    { number: '29', color: ':black_circle:' },
    { number: '7', color: ':red_circle:' },
    { number: '28', color: ':black_circle:' },
    { number: '12', color: ':red_circle:' },
    { number: '35', color: ':black_circle:' },
    { number: '3', color: ':red_circle:' },
    { number: '26', color: ':black_circle:' }
];

module.exports = rouletteWheel;
